[crowsnest]
log_path: /home/J.3D/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: false
no_proxy: false

[cam 1]
mode: ustreamer
enable_rtsp: false
rtsp_port: 8554
port: 8080
device: /dev/v4l/by-id/usb-Trust_Webcam_Trust_Webcam_20200907-video-index0
resolution: 640x480
max_fps: 15
custom_flags: --format=mjpeg

[cam 2]
mode: ustreamer
enable_rtsp: false
rtsp_port: 8555
port: 8081
device: /dev/v4l/by-id/usb-046d_HD_Pro_Webcam_C920_EB2F7E8F-video-index0
resolution: 640x480
max_fps: 15
custom_flags: --format=mjpeg
